apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: {{ .Release.Name }}-demodb
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
spec:
  configurations:
    backups:
      - sgObjectStorage: {{ .Release.Name }}-minio
        {{ if .Values.backupschedule.backupretentioncount }}
        cronSchedule: "{{ .Values.backupschedule.backupminute }} {{ .Values.backupschedule.backuphour }} * * {{ .Values.backupschedule.backupdayofweek }}"
        compression: lz4
        retention: {{ .Values.backupschedule.backupretentioncount }}
        {{ end }}
  {{ if ((.Values.init).username) }}
  managedSql:
    scripts:
      - sgScript: {{ .Release.Name }}-sgscript-initialization
  {{ end }}
  pods:
    persistentVolume:
      size: {{ .Values.sgcluster.disksizegb }}Gi
  postgres:
    version: {{ .Values.sgcluster.version }}
  instances: 2
  profile: {{ .Values.sgcluster.profile }}
  {{ if ((.Values.prometheus).enabled) }}
  prometheusAutobind: true
  {{ end }}
