apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      app.openshift.io/route-disabled: "false"
      app.openshift.io/vcs-ref: ""
      app.openshift.io/vcs-uri: https://github.com/schoolofdevops/html-sample-app/
      deployment.kubernetes.io/revision: "1"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"html5-app:latest","namespace":"myhhtp"},"fieldPath":"spec.template.spec.containers[?(@.name==\"html5-app\")].image","paused":"false"}]'
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2025-02-15T14:59:31Z"
    generation: 1
    labels:
      app: html5-app
      app.kubernetes.io/component: html5-app
      app.kubernetes.io/instance: html5-app
      app.kubernetes.io/name: html5-app
      app.kubernetes.io/part-of: html5-app
      app.openshift.io/runtime: httpd
      app.openshift.io/runtime-version: 2.4-el7
    name: html5-app
    namespace: myhhtp
    resourceVersion: "207097"
    uid: 72c8ece9-5785-41e2-9cf9-acaae1ba5deb
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: html5-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: html5-app
          deployment: html5-app
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/myhhtp/html5-app:latest
          imagePullPolicy: Always
          name: html5-app
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-02-15T15:02:54Z"
      lastUpdateTime: "2025-02-15T15:02:54Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-02-15T14:59:31Z"
      lastUpdateTime: "2025-02-15T15:02:54Z"
      message: ReplicaSet "html5-app-79744bb489" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
