apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/vcs-ref: ""
      app.openshift.io/vcs-uri: https://github.com/schoolofdevops/html-sample-app/
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2025-02-15T14:59:31Z"
    labels:
      app: html5-app
      app.kubernetes.io/component: html5-app
      app.kubernetes.io/instance: html5-app
      app.kubernetes.io/name: html5-app
      app.kubernetes.io/part-of: html5-app
      app.openshift.io/runtime: httpd
      app.openshift.io/runtime-version: 2.4-el7
    name: html5-app
    namespace: myhhtp
    resourceVersion: "206372"
    uid: f819c6a0-9da3-4334-a783-7bf69d9b1115
  spec:
    clusterIP: 10.217.4.78
    clusterIPs:
    - 10.217.4.78
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: html5-app
      deployment: html5-app
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
