apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: demodb
spec:
  configurations:
    backups:
      - sgObjectStorage: minio
        cronSchedule: "*/5 * * * *"
        compression: lz4
        retention: 8
  pods:
    persistentVolume:
      size: 20Gi
  postgres:
    version: latest
  instances: 2
  profile: development

