apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: demodb
spec:
  configurations:
    backups:
      - sgObjectStorage: minio
  pods:
    persistentVolume:
      size: 20Gi
  postgres:
    version: latest
  instances: 2
  profile: development

