{{- if ((.Values.init).username) }}
{{- if (((.Values.init).userobjects).database) }}
{{- if (((.Values.init).userobjects).initsql) }}
apiVersion: v1
data:
  initsql: {{ .Values.init.initsql }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-initsql
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
{{- end }}
{{- end }}
{{- end }}