apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-minio
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
data:
  accesskey: {{ .Values.minio.accesskey | b64enc | quote }}
  secretkey: {{ .Values.minio.secretkey | b64enc | quote }}
type: Opaque
