{{-  $createusersql := printf "CREATE USER %s with password '%s';" .Values.init.username .Values.init.password -}}
apiVersion: v1
data:
  create-user: "{{ $createusersql | b64enc }}"
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-user-initalization
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
