{{- if ((.Values.init).username) }}
apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: {{ .Release.Name }}-sgscript-initialization
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
spec:
  managedVersions: true
  continueOnError: false
  scripts:
  - name: create-user
    scriptFrom:
      secretKeyRef: 
        name: {{ .Release.Name }}-secret-user-initalization
        key: create-user
  {{- if (((.Values.init).userobjects).database) }}
  - name: create-database
    script: |
            CREATE DATABASE {{ .Values.init.database }} 
            WITH OWNER {{ .Values.init.username }};
  {{- if (((.Values.init).userobjects).initsql) }}
  - name: initsql
    database: {{ .Values.init.userobjects.database }}
    scriptFrom:
      configMapKeyRef:
        name: {{ .Release.Name }}-configmap-initsql
        key: initsql
  {{- end }}
  {{- end }}
{{- end }}
