apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-k8s-global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-k8s
subjects:
- kind: User
  name: system:serviceaccount:openshift-monitoring:prometheus-k8s
  apiGroup: rbac.authorization.k8s.io


