apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demodb
  name: prometheus-rule-manager
rules:
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules"]
  verbs: ["create", "update", "delete", "get", "list", "watch"]

