apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: demodb
  name: prometheus-rule-manager-binding
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prometheus-rule-manager
  apiGroup: rbac.authorization.k8s.io

